Library exercise for achievement network.
liquidity-network/template.achievement.network pull request #7
Opened 2019-01-22 16:00 UTC by wakeuprj

2019-01-28 02:28 UTC, nud3l commented
Thanks for committing this. Please add your commit so a separate file.

A shortcoming of your code is, that you cannot add more books in the process. So what happends if the library gets and receives more books?

2019-01-28 02:58 UTC, nud3l requested changes
Do not edit MODIFY_ME.

2019-01-28 10:49 UTC, wakeuprj commented
HI Dominik, I've updated such that I don't modify EXAMPLE.md anymore. Also, thanks for pointing out that we can't add books to the library. It was a conscious decision since I wanted to make the code easy to read and understand. Although, adding that functionality should be straight forward as well (could be a nice extension to the exercise).

2019-01-29 01:29 UTC, nud3l approved these changes

2019-04-08 10:41 UTC, closed without merging